version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - "5432:5432"
    networks:
      - restbase

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      STAGE: test
    ports:
      - "5000:80"
    networks:
      - restbase

networks:
  restbase:
    driver: bridge
