version: '3'
services:
  postgres_internal:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - default

  postgres_test_base:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - default

  api:
    build: .
    depends_on:
      - postgres_internal
      - postgres_test_base
    environment:
      STAGE: test
    networks:
      - default

networks:
  default:
    driver: bridge
