version: '3'
services:
  postgres_internal:
    image: "postgres" # use latest official postgres version
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      - postgres_internal
    environment:
      STAGE: test
    networks:
      - default

networks:
  default:
    driver: bridge
